name: Shared CI Workflow

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: false
      target-branch:
        required: false
        type: string
        default: ''

jobs:
  build:
    name: ${{ inputs.job-name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JDK_VERSION }}

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github-elara-app-validations-test</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Verify
        run: mvn clean verify --batch-mode

      - name: Show Maven Settings.xml for Debugging
        run: cat ~/.m2/settings.xml

      - name: Deploy to Maven (if enabled)
        if: ${{ inputs.deploy == true }}
        run: mvn deploy -DskipTests
