name: Shared CI Workflow

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: false
      target-branch:
        required: false
        type: string
        default: ''

jobs:
  build:
    name: ${{ inputs.job-name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: ${{ vars.JDK_VERSION }}
          server-id: "github-releases"
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set JDK Version
        run: echo "JDK_VERSION=${{ vars.JDK_VERSION }}"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Verify
        run: mvn clean verify --batch-mode

      - name: Show Maven Settings.xml for Debugging
        run: cat ~/.m2/settings.xml

      - name: Deploy to Maven (if enabled)
        if: ${{ inputs.deploy == true }}
        run: mvn deploy -DskipTests
